### ISSUE TITLE
Unexpected duplicate props and <deprecated> elements

### ISSUE THREAD

**Issue by pan-zhuo** [uwlib-cams/map_storage#37]
It seems that [a recent commit](https://github.com/uwlib-cams/map_storage/commit/558f11b1b4874eda768f644672ad8cc34e5887f9) has created unexpected duplicate props in the prop sets that I have worked on. The props that I had configured were also 'deprecated'.

https://github.com/uwlib-cams/map_storage/blob/f570e1152936fdbc5c6f0c75d67183fc546038c8/prop_set_rdaw_p10k.xml#L3128-L3145

A search for 'w/P10331' returned 2 hits.

I manually resolved the conflicts in rdam, but I pulled the current version of rdaw...

**Comment by briesenberg07** [comment]
Hi @cspayne 
Was this an unexpected result of the work to add the uwsinopia namespace back into prop_sets? These changes look to have come in on [the commit where namespaces were updated](https://github.com/uwlib-cams/map_storage/commit/558f11b1b4874eda768f644672ad8cc34e5887f9).

**Comment by briesenberg07** [comment]
Per @pan-zhuo \:

- Manifestation fixed manually
- Issues in Work, Nomen

The problems seem to be in prop_sets where work has taken place?

**Comment by cspayne** [comment]
The issue appeared to be caused by the reformatting done in update_prop_sets.py after an update, causing the program to fail to recognize properties when run a again.
This has now been fixed and tested!
All prop_sets should be back to normal and usable (but let me know if not). 

@pan-zhuo @briesenberg07
